In [1]:
import pandas as pd
import numerapi

In [2]:
training_data = pd.read_csv("https://numerai-public-datasets.s3-us-west-2.amazonaws.com/latest_numerai_training_data.csv.xz")

In [3]:
training_data.shape

(501808, 314)

In [4]:
training_data[['target_kazutsugi', 'id']].groupby('target_kazutsugi').count()

                      id
target_kazutsugi
0.00              100042
0.25              100046
0.50              101632
0.75              100041
1.00              100047

In [5]:
training_data.groupby('era').count()

,id,data_type,feature_intelligence1,feature_intelligence2,feature_intelligence3,feature_intelligence4,feature_intelligence5,feature_intelligence6,feature_intelligence7,feature_intelligence8,...,feature_wisdom38,feature_wisdom39,feature_wisdom40,feature_wisdom41,feature_wisdom42,feature_wisdom43,feature_wisdom44,feature_wisdom45,feature_wisdom46,target_kazutsugi
era,,,,,,,,,,,,,,,,,,,,,
era1,2408,2408,2408,2408,2408,2408,2408,2408,2408,2408,...,2408,2408,2408,2408,2408,2408,2408,2408,2408,2408
era10,3336,3336,3336,3336,3336,3336,3336,3336,3336,3336,...,3336,3336,3336,3336,3336,3336,3336,3336,3336,3336
era100,4748,4748,4748,4748,4748,4748,4748,4748,4748,4748,...,4748,4748,4748,4748,4748,4748,4748,4748,4748,4748
era101,4730,4730,4730,4730,4730,4730,4730,4730,4730,4730,...,4730,4730,4730,4730,4730,4730,4730,4730,4730,4730
era102,4704,4704,4704,4704,4704,4704,4704,4704,4704,4704,...,4704,4704,4704,4704,4704,4704,4704,4704,4704,4704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
era95,4534,4534,4534,4534,4534,4534,4534,4534,4534,4534,...,4534,4534,4534,4534,4534,4534,4534,4534,4534,4534
era96,4658,4658,4658,4658,4658,4658,4658,4658,4658,4658,...,4658,4658,4658,4658,4658,4658,4658,4658,4658,4658
era97,4696,4696,4696,4696,4696,4696,4696,4696,4696,4696,...,4696,4696,4696,4696,4696,4696,4696,4696,4696,4696
era98,4717,4717,4717,4717,4717,4717,4717,4717,4717,4717,...,4717,4717,4717,4717,4717,4717,4717,4717,4717,4717
era99,4749,4749,4749,4749,4749,4749,4749,4749,4749,4749,...,4749,4749,4749,4749,4749,4749,4749,4749,4749,4749

In [6]:
set([col.strip('1234567890') for col in training_data.columns])

{'data_type',
 'era',
 'feature_charisma',
 'feature_constitution',
 'feature_dexterity',
 'feature_intelligence',
 'feature_strength',
 'feature_wisdom',
 'id',
 'target_kazutsugi'}

In [ ]:
tournament_data = pd.read_csv("https://numerai-public-datasets.s3-us-west-2.amazonaws.com/latest_numerai_tournament_data.csv.xz")
tournament_data.head()

In [ ]:
tournament_data.groupby('data_type').count()

In [ ]:
tournament_data[tournament_data['data_type']=='validation'].groupby('era').count()